name: docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.GHCR_KEY }}  
      run: |
        echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USER --password-stdin
    - name: docker build leaf
      run: |
        docker build . -t ghcr.io/${{ github.repository_owner }}/leaf:latest  
    - name: docker push
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/leaf:latest
