name: docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login ghcr.io -u DOCKER_USER -p $GHCR_KEY
    - name: docker build leaf
      run: |
        docker build . -t withs/leaf:1.0.0
    - name: docker push
      run: |
        docker push ghcr.io/withs/leaf:1.0.0
